{"name": "test_login_fail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: 显示等待查找失败\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x007B6E73+48323]\n\t(No symbol) [0x00749661]\n\t(No symbol) [0x00655308]\n\t(No symbol) [0x00680B45]\n\t(No symbol) [0x00680CDB]\n\t(No symbol) [0x006AE3D2]\n\t(No symbol) [0x0069A924]\n\t(No symbol) [0x006ACAC2]\n\t(No symbol) [0x0069A6D6]\n\t(No symbol) [0x0067847C]\n\t(No symbol) [0x0067957D]\n\tGetHandleVerifier [0x00A1FD5D+2575277]\n\tGetHandleVerifier [0x00A5F86E+2836158]\n\tGetHandleVerifier [0x00A596DC+2811180]\n\tGetHandleVerifier [0x008441B0+626688]\n\t(No symbol) [0x0075314C]\n\t(No symbol) [0x0074F4B8]\n\t(No symbol) [0x0074F59B]\n\t(No symbol) [0x007421B7]\n\tBaseThreadInitThunk [0x76BA00C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x76F57B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x76F57B1E+238]", "trace": "self = <testcases.test_login.Testlogin object at 0x000002323624A490>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"3898a6e2e23cc5825155698a765788bd\")>\n\n    @allure.epic(\"登录\")\n    @allure.feature(\"用户名为空时，测试是否登录失败\")\n    @allure.description(\"用户名为空，密码正确输入，测试是否登录失败\")\n    def test_login_fail(self, driver):\n        \"\"\"\n        使用正确的账号登录\n        :param driver:\n        :return:\n        \"\"\"\n        with allure.step(\"登录\"):\n            LoginPage().login_fail(driver)\n        with allure.step(\"断言登录后文本为登录成功\"):\n>           login_text = LoginPage().assert_login_success(driver)\n\ntestcases\\test_login.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npage\\Loginpage.py:107: in assert_login_success\n    login_element = WebDriverWait(driver, 10, 0.5).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"3898a6e2e23cc5825155698a765788bd\")>\nmethod = <function LoginPage.assert_login_success.<locals>.<lambda> at 0x0000023236189700>\nmessage = '显示等待查找失败'\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: 显示等待查找失败\nE       Stacktrace:\nE       Backtrace:\nE       \tGetHandleVerifier [0x007B6E73+48323]\nE       \t(No symbol) [0x00749661]\nE       \t(No symbol) [0x00655308]\nE       \t(No symbol) [0x00680B45]\nE       \t(No symbol) [0x00680CDB]\nE       \t(No symbol) [0x006AE3D2]\nE       \t(No symbol) [0x0069A924]\nE       \t(No symbol) [0x006ACAC2]\nE       \t(No symbol) [0x0069A6D6]\nE       \t(No symbol) [0x0067847C]\nE       \t(No symbol) [0x0067957D]\nE       \tGetHandleVerifier [0x00A1FD5D+2575277]\nE       \tGetHandleVerifier [0x00A5F86E+2836158]\nE       \tGetHandleVerifier [0x00A596DC+2811180]\nE       \tGetHandleVerifier [0x008441B0+626688]\nE       \t(No symbol) [0x0075314C]\nE       \t(No symbol) [0x0074F4B8]\nE       \t(No symbol) [0x0074F59B]\nE       \t(No symbol) [0x007421B7]\nE       \tBaseThreadInitThunk [0x76BA00C9+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x76F57B4E+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x76F57B1E+238]\n\nD:\\apache-maven-3.8.5-bin\\pythonWeb\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "用户名为空，密码正确输入，测试是否登录失败", "steps": [{"name": "登录", "status": "passed", "start": 1687777262724, "stop": 1687777268717}, {"name": "断言登录后文本为登录成功", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: 显示等待查找失败\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x007B6E73+48323]\n\t(No symbol) [0x00749661]\n\t(No symbol) [0x00655308]\n\t(No symbol) [0x00680B45]\n\t(No symbol) [0x00680CDB]\n\t(No symbol) [0x006AE3D2]\n\t(No symbol) [0x0069A924]\n\t(No symbol) [0x006ACAC2]\n\t(No symbol) [0x0069A6D6]\n\t(No symbol) [0x0067847C]\n\t(No symbol) [0x0067957D]\n\tGetHandleVerifier [0x00A1FD5D+2575277]\n\tGetHandleVerifier [0x00A5F86E+2836158]\n\tGetHandleVerifier [0x00A596DC+2811180]\n\tGetHandleVerifier [0x008441B0+626688]\n\t(No symbol) [0x0075314C]\n\t(No symbol) [0x0074F4B8]\n\t(No symbol) [0x0074F59B]\n\t(No symbol) [0x007421B7]\n\tBaseThreadInitThunk [0x76BA00C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x76F57B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x76F57B1E+238]\n\n", "trace": "  File \"D:\\web\\testcases\\test_login.py\", line 44, in test_login_fail\n    login_text = LoginPage().assert_login_success(driver)\n  File \"D:\\web\\page\\Loginpage.py\", line 107, in assert_login_success\n    login_element = WebDriverWait(driver, 10, 0.5).until(\n  File \"D:\\apache-maven-3.8.5-bin\\pythonWeb\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1687777268717, "stop": 1687777279202}], "attachments": [{"name": "失败截图.png", "source": "504d8133-c33b-4f16-96a8-f07e36476046-attachment.png", "type": "image/png"}, {"name": "log", "source": "02138bed-ece8-44b6-ba15-3fef80766bfe-attachment.txt", "type": "text/plain"}], "start": 1687777262724, "stop": 1687777279203, "uuid": "eace87c2-d2ce-437b-a70e-a9be966fdafc", "historyId": "294eea966cc3df74d371fd0a1a5e2d7b", "testCaseId": "fc2e9c8ba71d3fe9851dbf728592ea1a", "fullName": "testcases.test_login.Testlogin#test_login_fail", "labels": [{"name": "epic", "value": "登录"}, {"name": "feature", "value": "用户名为空时，测试是否登录失败"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "LAPTOP-8TMKGH6U"}, {"name": "thread", "value": "19960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}